### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by strukturart** [strukturart/watermelon#2]
- [x] exchange send - receive message
- [ ] settings metered.ca api key
- [x] fix liveLocationSharing
- [x] Contact list with last received message
- [ ] Notes

**Comment by crislobo-alt** [comment]
are push notifications available at the moment?

**Comment by strukturart** [comment]
yes, but I am still working on the reliability
